[project]
name = "mo3d"
version = "0.1.0"
description = "Prototype 3d library for Mojo Lang"
authors = ["Thomas Gale <mail@thomasjamesgale.com>"]
license = "Apache-2.0"
readme = "README.md"
channels = ["conda-forge", "https://conda.modular.com/max"]
platforms = ["linux-64"]

[tasks]

[dependencies]
max = ">=24.4.0dev7,<24.5"
numpy = ">=2.0.1,<2.1"
