[project]
name = "mo3d"
version = "0.1.0"
description = "Prototype 3d library for Mojo Lang"
authors = ["Thomas Gale <mail@thomasjamesgale.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
readme = "README.md"
license = "Apache-2.0"
platforms = ["linux-64", "osx-arm64"]

[tasks]
start = { cmd = "mojo run src/main.mojo", depends-on = ["setup"] }
package = { cmd = "mkdir -p bin && magic run mojo package src/mo3d -o bin/mo3d.mojopkg && cp bin/mo3d.mojopkg test/mo3d/mo3d.mojopkg", depends-on = ["setup"], inputs=["src/*.mojo"], outputs = ["bin/mo3d.mojopkg", "test/mo3d/mo3d.mojopkg"] }
test = { cmd = "magic run mojo test ./test", depends-on = ["package"] }
build = { cmd = "mkdir -p bin && magic run mojo build src/main.mojo -o bin/mo3d", depends-on = ["setup"], inputs=["src/*.mojo"], outputs = ["bin/mo3d"] }
built = { cmd = "bin/mo3d", depends-on = ["build"] }

[dependencies]
max = ">=24.6.0.dev2024091205,<25"

[target.linux-64.tasks]
setup = { cmd="sudo apt update && sudo apt install -y llvm libsdl2-dev", inputs=["pixi.toml"] }

[target.osx-arm64.tasks]
setup = { cmd="brew install llvm sdl2", inputs=["pixi.toml"] }
